export const STATUS = {
  NOT_STARTED: "NOT_STARTED",
  IN_PROGRESS: "IN_PROGRESS",
  ANSWERED: "ANSWERED",
};

export const LANGUAGES = {
  EN: "EN",
  RO: "RO",
};

export const REMAINING_QUESTIONS = "REMAINING_QUESTIONS";
export const TEST_ENV_REMAINING_QUESTIONS = "TEST_ENV_REMAINING_QUESTIONS";

export const TEST_QUESTIONS_COUNT = 90;
