export const STATUS = {
  NOT_STARTED: "NOT_STARTED",
  IN_PROGRESS: "IN_PROGRESS",
  ANSWERED: "ANSWERED",
};

export const LANGUAGES = {
  EN: "EN",
  RO: "RO",
};

export const REMAINING_QUESTIONS = "REMAINING_QUESTIONS";
